# Generated by Django 4.1.1 on 2022-09-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindermodel',
            name='task',
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='selected_color',
            field=models.CharField(blank=True, choices=[(None, 'Сolorless'), ('#FF0000', 'Red'), ('#FF8000', 'Orange'), ('#FFFF00', 'Yellow'), ('#7FFF00', 'Green'), ('#0000FF', 'Blue'), ('#00FFFF', 'Cyan'), ('#8A2BE2', 'Purple')], default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reminder.taskmodel'),
        ),
    ]
