# Generated by Django 4.1.1 on 2022-09-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_remove_remindermodel_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
