# Generated by Django 4.1.1 on 2022-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_delete_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='selected_color',
            field=models.CharField(choices=[('#ff000000', 'Сolorless'), ('#FF0000af', 'Red'), ('#FF8000af', 'Orange'), ('#FFFF00af', 'Yellow'), ('#00DD1Daf', 'Green'), ('#0084FFaf', 'Blue'), ('#00FFFFaf', 'Cyan'), ('#8A2BE2af', 'Purple')], default='#ff000000', max_length=10),
        ),
    ]
