# Generated by Django 4.1.1 on 2022-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_alter_remindermodel_selected_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='selected_color',
            field=models.CharField(choices=[('hsv(0,100,100)', 'Сolorless'), ('hsv(0,100,100)', 'Red'), ('hsv(31,100,100)', 'Orange'), ('hsv(60,100,100)', 'Yellow'), ('hsv(128,100,87)', 'Green'), ('hsv(180,100,100)', 'Cyan'), ('hsv(209,100,100)', 'Blue'), ('hsv(272,81,89)', 'Purple')], default='#ff000000', max_length=100),
        ),
    ]
