# Generated by Django 4.1.1 on 2022-11-04 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0009_alter_remindermodel_selected_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='selected_color',
            field=models.CharField(choices=[('7', 'Сolorless'), ('0', 'Red'), ('1', 'Orange'), ('2', 'Yellow'), ('3', 'Green'), ('4', 'Cyan'), ('5', 'Blue'), ('6', 'Purple')], default='7', max_length=100),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
